exclude:
  - '*.kicad_pcb'
  - '*.kicad_pro'
  - '*.kicad_sch'
  - '*.sketch'
  - '*.kicad_mod'
  - '*.ino'
  - '*.dxf'
  - '*.pretty'
domain: docs.paleslimghost.store
url: https://docs.paleslimghost.store
